# PROJEKT : Polizeikontrollen im Straßenverkehr (EDA)

Bevor Sie mit Ihrer Analyse beginnen, ist es entscheidend, dass Sie den Datensatz zunächst untersuchen und bereinigen, um eine effizientere Verarbeitung zu ermöglichen.  
Dabei werden Sie üben, Datentypen zu korrigieren, mit fehlenden Werten umzugehen sowie unnötige Spalten und Zeilen zu entfernen – und das alles im Rahmen der Arbeit mit dem Datensatz des Stanford Open Policing Project.

##  Untersuchung des Datensatzes

Sie werden einen Datensatz von Verkehrskontrollen im Bundesstaat Rhode Island analysieren, der vom Stanford Open Policing Project gesammelt wurde.

Bevor Sie mit der Analyse beginnen, ist es wichtig, dass Sie sich mit dem Datensatz vertraut machen.  
Sie werden den Datensatz mit pandas einlesen, die ersten paar Zeilen untersuchen und dann die Anzahl fehlender Werte zählen.

### ANWEISUNGEN

- Importieren Sie `pandas` mit dem Alias `pd`.
- Lesen Sie die Datei `police.csv` in ein DataFrame mit dem Namen `ri` ein.
- Untersuchen Sie die ersten 5 Zeilen des DataFrames (bekannt als „head“).
- Zählen Sie die Anzahl fehlender Werte in jeder Spalte: Verwenden Sie `.isnull()`, um zu prüfen, welche Elemente im DataFrame fehlen, und anschließend `.sum()`, um die Anzahl der `True`-Werte (also der fehlenden Werte) in jeder Spalte zu ermitteln.

## 1. Datenimport und Bibliotheken

In [1]:
import pandas as pd
import numpy as np

# Lese die ersten 50.000 Zeilen der Datei "RI_cleaned.csv" in ein DataFrame namens 'ri' ein
ri = pd. read_csv("RI_cleaned.csv", nrows=50000 )

/var/folders/bb/6m7zfmqn4dlckynjdkxpvrrr0000gn/T/ipykernel_9159/27375258.py:5: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  ri = pd. read_csv("RI_cleaned.csv", nrows=50000 )

## 2. Überblick über den Datensatz

In [2]:
ri.head()

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,RI-2005-00001,RI,2005-01-02,01:55,Zone K1,NaN,NaN,NaN,600,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,RI-2005-00002,RI,2005-01-02,20:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,RI-2005-00003,RI,2005-01-04,11:30,Zone X1,NaN,NaN,NaN,0,NaN,...,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,Zone X1
3,RI-2005-00004,RI,2005-01-04,12:55,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,RI-2005-00005,RI,2005-01-06,01:30,Zone X4,NaN,NaN,NaN,500,M,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4

In [3]:
ri.columns

Index(['id', 'state', 'stop_date', 'stop_time', 'location_raw', 'county_name',
       'county_fips', 'fine_grained_location', 'police_department',
       'driver_gender', 'driver_age_raw', 'driver_age', 'driver_race_raw',
       'driver_race', 'violation_raw', 'violation', 'search_conducted',
       'search_type_raw', 'search_type', 'contraband_found', 'stop_outcome',
       'is_arrested', 'stop_duration', 'out_of_state', 'drugs_related_stop',
       'district'],
      dtype='object')

In [4]:
# Zähle die Anzahl der fehlenden Werte pro Spalte
ri.isnull()

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,True,True,True,False,True,...,False,True,True,False,True,True,True,True,False,False
3,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
4,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
49996,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
49997,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
49998,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
49999,False,False,False,False,False,True,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False

In [5]:
ri.isnull().sum()

id                           0
state                        0
stop_date                    0
stop_time                    0
location_raw                 0
county_name              50000
county_fips              50000
fine_grained_location    50000
police_department            0
driver_gender             1990
driver_age_raw            1971
driver_age                2208
driver_race_raw           1988
driver_race               1988
violation_raw             1988
violation                 1988
search_conducted             0
search_type_raw          47988
search_type              47988
contraband_found             0
stop_outcome              1988
is_arrested               1988
stop_duration             1988
out_of_state              2203
drugs_related_stop           0
district                     0
dtype: int64

In [6]:
# Zeige die Dimensionen des DataFrames als (Zeilen, Spalten) an
ri.shape

(50000, 26)

In [7]:
# Liste der Spalten, die aus dem DataFrame entfernt werden sollen
drop_columns = (["state", "county_name", "county_fips", "fine_grained_location"])

In [8]:
# Entferne die angegebenen Spalten (axis=1 bedeutet Spalten) dauerhaft (inplace=True) aus dem DataFrame
ri.drop(drop_columns, axis = 1, inplace=True)

In [9]:
ri.shape  # Wir haben 4 Spalten entfernt

(50000, 22)

## 3. Datenbereinigung durch Zeilenlöschung

Wenn Sie wissen, dass eine bestimmte Spalte für Ihre Analyse entscheidend ist und nur ein kleiner Teil der Zeilen in dieser Spalte fehlende Werte enthält, ist es oft sinnvoll, diese Zeilen aus dem Datensatz zu entfernen.

In diesem Kurs wird die Spalte `driver_gender` für viele Analysen von zentraler Bedeutung sein.  
Da nur ein kleiner Teil der Zeilen in dieser Spalte fehlende Werte enthält, werden wir diese Zeilen aus dem Datensatz entfernen.

### ANWEISUNGEN

- Zählen Sie die Anzahl fehlender Werte in jeder Spalte.
- Entfernen Sie alle Zeilen, in denen `driver_gender` fehlt, indem Sie den Spaltennamen als `subset`-Parameter an `.dropna()` übergeben.
- Zählen Sie die fehlenden Werte erneut, um zu überprüfen, dass keine verbleibenden Zeilen `driver_gender` fehlen.
- Überprüfen Sie die `.shape` des DataFrames, um zu sehen, wie viele Zeilen und Spalten nach dem Entfernen übrig bleiben.

Wenn Sie wissen, dass eine bestimmte Spalte für Ihre Analyse entscheidend ist und nur ein kleiner Teil der Zeilen in dieser Spalte fehlende Werte enthält, ist es oft sinnvoll, diese Zeilen aus dem Datensatz zu entfernen.

Die Spalte `driver_gender` wird für den Großteil meiner Analysen von zentraler Bedeutung sein.  
Da nur wenige Zeilen keinen Wert in dieser Spalte enthalten, werden wir diese Zeilen aus dem Datensatz entfernen.

In [10]:
ri.isnull().sum()  # Fehlende Werte prüfen

id                        0
stop_date                 0
stop_time                 0
location_raw              0
police_department         0
driver_gender          1990
driver_age_raw         1971
driver_age             2208
driver_race_raw        1988
driver_race            1988
violation_raw          1988
violation              1988
search_conducted          0
search_type_raw       47988
search_type           47988
contraband_found          0
stop_outcome           1988
is_arrested            1988
stop_duration          1988
out_of_state           2203
drugs_related_stop        0
district                  0
dtype: int64

Die Spalte `driver_gender` ist für meine Analysen entscheidend.  
Da nur wenige Zeilen dort fehlende Werte enthalten, werden diese aus dem Datensatz entfernt.

In [11]:
# drop : Entfernt angegebene Zeilen oder Spalten
# dropna : Entfernt Zeilen mit fehlenden Werten (NaN)
# drop_duplicates : Entfernt doppelte Einträge
# Hier verwenden wir dropna, um Zeilen ohne 'driver_gender' zu entfernen

ri.dropna(subset=["driver_gender"], inplace=True)

In [12]:
ri.shape  # etwa 2000 Zeilen wurden entfernt

(48010, 22)

In [13]:
ri.isnull().sum()

id                        0
stop_date                 0
stop_time                 0
location_raw              0
police_department         0
driver_gender             0
driver_age_raw            0
driver_age              232
driver_race_raw           0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type_raw       45998
search_type           45998
contraband_found          0
stop_outcome              0
is_arrested               0
stop_duration             0
out_of_state            215
drugs_related_stop        0
district                  0
dtype: int64

Auch die Spalten `driver_race`, `driver_race_raw` und `driver_age` enthalten in denselben Zeilen fehlende Werte.  
Da wir Zeilen mit fehlendem `driver_gender` entfernt haben, wurden diese Werte ebenfalls mit entfernt.

## 4. Datentyp korrigieren

Wir wissen, dass die Spalte `is_arrested` derzeit den Datentyp „object“ hat, obwohl sie nur True- und False-Werte enthält.  
Daher werden wir den Datentyp in `bool` ändern, was für solche Werte am besten geeignet ist.

Die Korrektur des Datentyps ermöglicht uns, mathematische Operationen mit der Spalte `is_arrested` durchzuführen, die sonst nicht möglich wären.

**ANWEISUNGEN**

*   Untersuchen Sie den Anfang der Spalte `is_arrested`, um zu überprüfen, dass sie `True`- und `False`-Werte enthält.
*   Überprüfen Sie den aktuellen Datentyp von `is_arrested`.
*   Verwenden Sie die Methode `.astype()`, um `is_arrested` in eine `bool`-Spalte umzuwandeln.
*   Überprüfen Sie den neuen Datentyp, um sicherzustellen, dass `is_arrested` nun den Typ `bool` hat.

### Datentyp-Anpassung nach dem Drop

In [14]:
ri.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48010 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  48010 non-null  object
 1   stop_date           48010 non-null  object
 2   stop_time           48010 non-null  object
 3   location_raw        48010 non-null  object
 4   police_department   48010 non-null  object
 5   driver_gender       48010 non-null  object
 6   driver_age_raw      48010 non-null  float64
 7   driver_age          47778 non-null  float64
 8   driver_race_raw     48010 non-null  object
 9   driver_race         48010 non-null  object
 10  violation_raw       48010 non-null  object
 11  violation           48010 non-null  object
 12  search_conducted    48010 non-null  bool
 13  search_type_raw     2012 non-null   object
 14  search_type         2012 non-null   object
 15  contraband_found    48010 non-null  bool
 16  stop_outcome        48010 non-null  object
 17  is_arrested         48010 non-null  object
 18  stop_duration       48010 non-null  object
 19  out_of_state        47795 non-null  object
 20  drugs_related_stop  48010 non-null  bool
 21  district            48010 non-null  object
dtypes: bool(3), float64(2), object(17)
memory usage: 7.5+ MB

In [15]:
ri.dtypes

id                     object
stop_date              object
stop_time              object
location_raw           object
police_department      object
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race_raw        object
driver_race            object
violation_raw          object
violation              object
search_conducted         bool
search_type_raw        object
search_type            object
contraband_found         bool
stop_outcome           object
is_arrested            object
stop_duration          object
out_of_state           object
drugs_related_stop       bool
district               object
dtype: object

In [16]:
ri.is_arrested.head() # dtype ist object

0    False
1    False
3    False
4    False
5    False
Name: is_arrested, dtype: object

In [17]:
# Zeige den Datentyp des ersten Werts in der Spalte 'is_arrested'
type(ri.is_arrested.values[0])

bool

In [18]:
# Ändere den Datentyp der Spalte 'is_arrested' in bool
ri["is_arrested"] = ri.is_arrested.astype("bool")

In [19]:
ri["is_arrested"]

0        False
1        False
3        False
4        False
5        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Name: is_arrested, Length: 48010, dtype: bool

## 5. Zusammenführen von String-Spalten

Derzeit sind das Datum und die Uhrzeit jedes Polizeistopps in zwei separaten Objektspalten gespeichert: `stop_date` und `stop_time`.

Sie werden diese beiden Spalten zu einer einzigen Spalte kombinieren und anschließend in das Datumsformat (`datetime`) umwandeln.  
Dies ermöglicht den einfachen Zugriff auf datumsbezogene Attribute, die wir später im Projekt verwenden werden.

**ANWEISUNGEN**

- Verwenden Sie eine String-Methode, um `stop_date` und `stop_time` (getrennt durch ein Leerzeichen) zu verketten, und speichern Sie das Ergebnis in einer neuen Variable namens `combined`.
- Wandeln Sie `combined` in das Datumsformat (`datetime`) um und speichern Sie das Ergebnis in einer neuen Spalte namens `stop_datetime`.
- Untersuchen Sie die `.dtypes` des DataFrames, um zu bestätigen, dass `stop_datetime` nun den Typ `datetime` hat.

### Ich kombiniere die relevanten Spalten, um die Daten zu vereinfachen und den Fokus auf das Wesentliche der Analyse zu richten.

Jetzt werden wir aus den Spalten `stop_date` und `stop_time` eine einzelne Spalte erstellen und diese anschließend in das `datetime`-Format umwandeln.

In [20]:
ri.head()

,id,stop_date,stop_time,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,RI-2005-00001,2005-01-02,01:55,Zone K1,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,RI-2005-00002,2005-01-02,20:30,Zone X4,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
3,RI-2005-00004,2005-01-04,12:55,Zone X4,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,RI-2005-00005,2005-01-06,01:30,Zone X4,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
5,RI-2005-00006,2005-01-12,08:05,Zone X1,0,M,1973.0,32.0,B,Black,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

Ich werde zwei Pandas-Serien mit der Funktion `str.cat()` zusammenführen.  
Dabei übergebe ich `stop_date` an `.str.cat()` und verbinde es mit `ri.stop_time`.  
Das Ergebnis speichere ich in der Variablen `combined`.

In [21]:
# stop_date und stop_time verbinden
combined = ri.stop_date.str.cat(ri.stop_time, sep=" ")

# neue Serie mit Datum und Uhrzeit
combined

0        2005-01-02 01:55
1        2005-01-02 20:30
3        2005-01-04 12:55
4        2005-01-06 01:30
5        2005-01-12 08:05
               ...
49995    2006-08-08 22:45
49996    2006-08-08 22:45
49997    2006-08-08 22:53
49998    2006-08-08 23:00
49999    2006-08-08 23:00
Name: stop_date, Length: 48010, dtype: object

Jetzt erstelle ich die Spalte `stop_datetime`, der ich die Serie `combined` zuweise.  
Da sie sowohl Datum als auch Uhrzeit enthält, nenne ich sie `stop_datetime`.  
Ich konvertiere sie mit `to_datetime()` in den `datetime`-Typ, um anschließend Datumsfunktionen verwenden zu können.

In [22]:
# Neue datetime-Spalte erstellen
ri["stop_datetime"] = pd.to_datetime(combined)

In [23]:
# Alte Spalten entfernen
ri.drop(["stop_date", "stop_time"], axis="columns", inplace=True)

In [24]:
ri.head()

,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,violation,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,stop_datetime
0,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,Speeding,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,2005-01-02 01:55:00
1,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,Speeding,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,2005-01-02 20:30:00
3,RI-2005-00004,Zone X4,500,M,1986.0,19.0,W,White,Equipment/Inspection Violation,Equipment,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,2005-01-04 12:55:00
4,RI-2005-00005,Zone X4,500,M,1978.0,27.0,B,Black,Equipment/Inspection Violation,Equipment,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,2005-01-06 01:30:00
5,RI-2005-00006,Zone X1,0,M,1973.0,32.0,B,Black,Call for Service,Other,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,2005-01-12 08:05:00

In [25]:
ri.dtypes

id                            object
location_raw                  object
police_department             object
driver_gender                 object
driver_age_raw               float64
driver_age                   float64
driver_race_raw               object
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type_raw               object
search_type                   object
contraband_found                bool
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
out_of_state                  object
drugs_related_stop              bool
district                      object
stop_datetime         datetime64[ns]
dtype: object

## 6. Abschluss der Datenvorbereitung (EDA)

Der letzte Schritt in diesem Kapitel besteht darin, die Spalte `stop_datetime` als Index des DataFrames zu setzen.  
Durch den Ersatz des Standardindex mit einem `DatetimeIndex` wird die zeitbasierte Analyse erleichtert – was später im Projekt nützlich sein wird.

**ANWEISUNGEN**

- Setzen Sie `stop_datetime` als Index des DataFrames.
- Überprüfen Sie den Index und stellen Sie sicher, dass es sich um einen `DatetimeIndex` handelt.
- Kontrollieren Sie die Spalten, um zu bestätigen, dass `stop_datetime` nicht mehr unter den regulären Spalten ist.

In [26]:
ri.set_index("stop_datetime", inplace=True)

In [27]:
ri.head()

,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,violation,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,Speeding,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,Speeding,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 12:55:00,RI-2005-00004,Zone X4,500,M,1986.0,19.0,W,White,Equipment/Inspection Violation,Equipment,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,Zone X4,500,M,1978.0,27.0,B,Black,Equipment/Inspection Violation,Equipment,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-12 08:05:00,RI-2005-00006,Zone X1,0,M,1973.0,32.0,B,Black,Call for Service,Other,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

In [28]:
ri.shape

(48010, 20)

In [29]:
# 'stop_datetime' ist nicht mehr Spalte, sondern Index
ri.columns

Index(['id', 'location_raw', 'police_department', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race_raw', 'driver_race',
       'violation_raw', 'violation', 'search_conducted', 'search_type_raw',
       'search_type', 'contraband_found', 'stop_outcome', 'is_arrested',
       'stop_duration', 'out_of_state', 'drugs_related_stop', 'district'],
      dtype='object')

In [30]:
ri.to_csv("RI_08Feb.csv")  # Speichern des DataFrames in einer CSV-Datei

In [31]:
ri = pd.read_csv("RI_08Feb.csv")

ri.head()

/var/folders/bb/6m7zfmqn4dlckynjdkxpvrrr0000gn/T/ipykernel_9159/1204290996.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  ri = pd.read_csv("RI_08Feb.csv")

,stop_datetime,id,location_raw,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,violation_raw,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
0,2005-01-02 01:55:00,RI-2005-00001,Zone K1,600,M,1985.0,20.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
1,2005-01-02 20:30:00,RI-2005-00002,Zone X4,500,M,1987.0,18.0,W,White,Speeding,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2,2005-01-04 12:55:00,RI-2005-00004,Zone X4,500,M,1986.0,19.0,W,White,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
3,2005-01-06 01:30:00,RI-2005-00005,Zone X4,500,M,1978.0,27.0,B,Black,Equipment/Inspection Violation,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
4,2005-01-12 08:05:00,RI-2005-00006,Zone X1,0,M,1973.0,32.0,B,Black,Call for Service,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1